/*
================================================================================
PROJETO CRM - FARMÁCIAS SÃO JOÃO
QUERIES DE AQUISIÇÃO, LTV E FREQUÊNCIA
================================================================================

Estas queries foram projetadas para serem executadas no SNOWFLAKE.
Elas alimentam o dashboard CRM Analytics.
*/

-- 1. VOLUME DE CLIENTES NOVOS POR MÊS E ACUMULADO YTD
-- Objetivo: Identificar a entrada de novos CPFs na base e o crescimento anual.
WITH BASE_PRIMEIRA_COMPRA AS (
    SELECT
        CPF_CNPJ,
        DATE_TRUNC('MONTH', MIN(INCLUSAO_DATA)) AS MES_REFERENCIA
    FROM FSJ_PRD.GOLD.VW_ANALISE_VENDAS
    WHERE IDENTIFICADOR = 'V' -- Somente Vendas (ignora devoluções/recargas)
      AND CPF_CNPJ IS NOT NULL
    GROUP BY CPF_CNPJ
)
SELECT
    MES_REFERENCIA,
    COUNT(DISTINCT CPF_CNPJ) AS QTD_CLIENTES_NOVOS,
    SUM(COUNT(DISTINCT CPF_CNPJ)) OVER (
        PARTITION BY YEAR(MES_REFERENCIA) 
        ORDER BY MES_REFERENCIA
    ) AS NOVOS_CLIENTES_YTD
FROM BASE_PRIMEIRA_COMPRA
WHERE MES_REFERENCIA >= '2025-01-01'
GROUP BY MES_REFERENCIA
ORDER BY MES_REFERENCIA;


-- 2. LTV, FREQUÊNCIA E TICKET MÉDIO POR CANAL (HISTÓRICO)
-- Objetivo: Comparar a "qualidade" do cliente entre canais.
SELECT
    CASE
        WHEN TIPO_VENDA_DESCRICAO IN ('APP', 'APP Tele Entrega') THEN 'APP'
        WHEN TIPO_VENDA_DESCRICAO IN ('SITE', 'SITE Tele Entrega') THEN 'SITE'
        WHEN TIPO_VENDA_DESCRICAO IN ('Venda Balcão', 'Venda Caixa', 'Auto Atendimento') THEN 'LOJA FÍSICA'
        WHEN TIPO_VENDA_DESCRICAO IN ('Venda Tele Entrega', 'Tele Entrega Central') THEN 'TELEVENDAS'
        ELSE 'OUTROS'
    END AS CANAL,
    COUNT(DISTINCT CPF_CNPJ) AS QTD_CLIENTES_UNICOS,
    COUNT(DISTINCT VENDA_ID) AS QTD_COMPRAS,
    ROUND(SUM(VALOR_TOTAL), 2) AS RECEITA_TOTAL,
    ROUND(SUM(VALOR_TOTAL) / NULLIF(COUNT(DISTINCT CPF_CNPJ), 0), 2) AS LTV_HISTORICO,
    ROUND(COUNT(DISTINCT VENDA_ID) / NULLIF(COUNT(DISTINCT CPF_CNPJ), 0), 2) AS FREQUENCIA_MEDIA
FROM FSJ_PRD.GOLD.VW_ANALISE_VENDAS
WHERE IDENTIFICADOR = 'V'
  AND INCLUSAO_DATA >= '2025-01-01'
GROUP BY 1
ORDER BY LTV_HISTORICO DESC;


-- 3. MIX DE CANAL NA PRIMEIRA COMPRA (AQUISIÇÃO)
-- Objetivo: Identificar por qual canal os novos clientes estão entrando na São João.
WITH PRIMEIRA_COMPRA AS (
    SELECT 
        CPF_CNPJ, 
        MIN(INCLUSAO_DATA) AS DATA_PRIMEIRA
    FROM FSJ_PRD.GOLD.VW_ANALISE_VENDAS 
    WHERE IDENTIFICADOR = 'V' 
    GROUP BY CPF_CNPJ
)
SELECT
    DATE_TRUNC('MONTH', PC.DATA_PRIMEIRA) AS MES_AQUISICAO,
    CASE
        WHEN V.TIPO_VENDA_DESCRICAO IN ('APP', 'APP Tele Entrega') THEN 'APP'
        WHEN V.TIPO_VENDA_DESCRICAO IN ('SITE', 'SITE Tele Entrega') THEN 'SITE'
        WHEN V.TIPO_VENDA_DESCRICAO IN ('Venda Balcão', 'Venda Caixa', 'Auto Atendimento') THEN 'LOJA FÍSICA'
        WHEN V.TIPO_VENDA_DESCRICAO IN ('Venda Tele Entrega', 'Tele Entrega Central') THEN 'TELEVENDAS'
        ELSE 'OUTROS'
    END AS CANAL_AQUISICAO,
    COUNT(DISTINCT PC.CPF_CNPJ) AS QTD_NOVOS_CLIENTES
FROM PRIMEIRA_COMPRA PC
JOIN FSJ_PRD.GOLD.VW_ANALISE_VENDAS V 
  ON PC.CPF_CNPJ = V.CPF_CNPJ 
  AND PC.DATA_PRIMEIRA = V.INCLUSAO_DATA
WHERE PC.DATA_PRIMEIRA >= '2025-01-01'
GROUP BY 1, 2
ORDER BY 1, 2;
